### ISSUE TITLE
Compatibility with SeaMonkey

### ISSUE THREAD

**Issue by shakeyourbunny** [JustOff/ca-archive#14]
Hello,

I tried to add this addon to my Mozilla Seamonkey 2.49.3, but it is not able to install.

Sadly, it is also too big to try to convert it with https://addonconverter.fotokraina.com/convert.php .

Could you add Mozilla Seamonkey compatibility please (in best case, there is only stuff to add in install.rdf)?

**Comment by JustOff** [comment]
Why do you need this, given that CAA only lists Firefox extensions and https://addons.thunderbird.net/en-US/seamonkey/ exists?

**Comment by TeoTwawki** [comment]
likely doing what I used to: modify the file to allow a firefox only addon to work in seamonkey because 9 of 10 times that's all it takes to make it work

**Comment by JustOff** [comment]
Well, I made the necessary changes that allow CAA to work in SeaMonkey, you can test this beta: [ca-archive-1.1.5b1.xpi](https://github.com/JustOff/ca-archive/releases/download/1.1.4/ca-archive-1.1.5b1.xpi).

However, it turned out that the SeaMonkey's session service does not handle the custom protocol urls properly. I reported this to the devs here: https://bugzilla.mozilla.org/show_bug.cgi?id=1492154.

**Comment by JustOff** [comment]
Resolved by [CAA 1.2.0](https://github.com/JustOff/ca-archive/releases/tag/1.2.0).
