### ISSUE TITLE
eset = fraud

### ISSUE THREAD

**Issue by thunderpants** [JustOff/ca-archive#25]
malwarebytes keeps flashing up a warning blocking ca-archive.biz - 
reason = fraud.
I know some *.biz links are used for bitcoin/mining scams so it's probably something related to that.
I've removed the addon for now.

LOGFILE:
Malwarebytes
www.malwarebytes.com

-Log Details-
Protection Event Date: 10/29/18
Protection Event Time: 1:20 AM
-System Information-
OS: Windows 10 (Build 17763.104)
CPU: x64
File System: NTFS
User: System

-Blocked Website Details-
Malicious Website: 1
, , Blocked, [-1], [-1],0.0.0

-Website Data-
Category: Fraud
Domain: ca-archive.biz.tm
IP Address: 104.28.13.152
Port: [51187]
Type: Outbound
File: C:\Program Files\Waterfox\waterfox.exe
(end)

**Comment by JustOff** [comment]
This is just a false positive alert, but it's up to you who to trust.

**Comment by grahamperrin** [comment]
From private messages in Reddit in October: 

> See for example https://imgsafe.org/image/03ddf869bc
> 
> I can raise a topic at https://forums.malwarebytes.com/forum/242-malwarebytes-for-firefox/ (not at https://forums.malwarebytes.com/forum/122-false-positives/) but I thought I should raise the issue with you first. 

– and: 

> To avoid any misunderstanding: I do not suspect fraud!
> 
> The link in the screenshot refers to generic https://blog.malwarebytes.com/glossary/fraud/?broext=1&x-source=fraud
> 
> I have seen a few blockages for 'possible suspicious activity' in the past, this may be the first time I have seen a fraud-oriented block by the extension.
> 
> A couple of quick guesses:
> 
> 1. the block was automated in response to detection of a prevalence of install-related files in a domain; and/or
> 2. a wilder guess, an .xpi file somewhere in the domain truly is (or was) associated with fraud, triggering a block on the entire domain.
> 
> HTH. Not raising alarm, just FYI.
> 
> Best, Graham

Now reported: 

- [false positive ca-archive.biz.tm - Malwarebytes for Firefox - Malwarebytes Forums](https://forums.malwarebytes.com/topic/239614-false-positive-ca-archivebiztm/)

**Comment by grahamperrin** [comment]
>> malwarebytes keeps flashing up a warning blocking …

<https://forums.malwarebytes.com/topic/239614-false-positive-ca-archivebiztm/?tab=comments#comment-1283432>: 

> Block has been removed.

**Comment by chocolateboy** [comment]
Is there a particular reason why the catalog is hosted on this domain (ca-archive.biz.tm), rather than e.g. ca-archive.waterfoxproject.org? The .biz (second-level) domain suggests a [commercial/monetized service](https://en.wikipedia.org/wiki/.biz):

> It is intended for registration of domains to be used by businesses.

I understand if it needs to be supported financially in some way (in addition to the donated storage space), particularly as free services like this can easily become unsustainable (e.g. [USO](https://news.ycombinator.com/item?id=1574840) and [OMDb](https://www.patreon.com/posts/api-is-going-10743518)). I'm just trying to clarify the relationship since I can't find any other info on this host.

**Comment by grahamperrin** [comment]
@JustOff @MrAlex94 ▲ above, re: the chosen domain I _guess_ that it's not e.g. `ca-archive.waterfoxproject.org` because projects (and persons) other than Waterfox might use the archived extensions, with or without the Classic Add-ons Archive front end. Fair guess?

@chocolateboy the linked Wikipedia page is for `.biz` not `.tm`.

[IANA — Root Zone Database](https://www.iana.org/domains/root/db) ▶ country-code `.tm` ▶ [NIC.TM - .TM Domain Registry and Network Information Centre](http://www.nic.tm/): 

> … We are the administrator of the .TM Top Level Domain Name …

– with [rules](http://www.nic.tm/rules.html) and a whois search field for _yourdomain_`.tm` through which you can get a result for `biz.tm`. For convenience: 

- http://www.nic.tm/cgi-bin/whois?query=biz.tm

Google found <https://website.informer.com/biz.tm>, with various tidbits, some of which might _appear_ to be inconsistent with the whois results above, and an invitation to _visit www.biz.tm_.

http://www.biz.tm/ redirects to <http://freedns.afraid.org/>, 

> FreeDNS - Free DNS - Dynamic DNS - Static DNS subdomain and domain hosting

**Comment by JustOff** [comment]
CAA is organized in a way I found most suitable for this, so please do not invent a conspiracy theory based on the domains and services involved.
