### ISSUE TITLE
It's nice but ...

### ISSUE THREAD

**Issue by grumpygeek** [JustOff/ca-archive#3]
putting an entire website into an extension is the wrong approach.  Even when it is changed later to point to a non-AMO site, it will still require users to update the 39MB extension to see one new extension.   I hate to see you put the time in on making an extension when it really should be a website.  If we get more or less the same thing hosted on an alternate website with it's own repository, then I'm not only in favor of it, I'd be willing to help.

**Comment by JustOff** [comment]
Since Mozilla declared they are going to remove all but WebExtensions from AMO, my original goal was to make my own local copy of all extensions. For this I needed a tool to check the integrity and completeness of this archive, thus CAA add-on was born.

It's not a perfect solution, but to date, as far as I know, it's the only one that already exists. Pale Moon and Waterfox teams are going to provide such archive as a vanilla website-based service, probably we will also see other alternatives, but now at least there is confidence that AMO data will not be lost.

**Comment by grumpygeek** [comment]
I know you said you're taking a break, but there is no reason why everyone should wait on or depend on Binary Outcast.  He doesn't have any more say over any of this than any of us.  I'd hate to see him take over (again).  We need some leaders who want rub everyone the wrong way.  A XUL dev site similar to moz-dev supported by volunteers would be good.  We also should not just archive the old ones but update and add new ones as well.
